# Generated by Django 5.2.7 on 2025-11-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_billing_bottles_alter_billing_food_and_more'),
    ]

    operations = [
    ]
